import express from 'express';
import multer from 'multer';
import sharp from 'sharp';
import archiver from 'archiver';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawn, spawnSync } from 'node:child_process';

const app=express();
const PORT=Number(process.env.PORT||10000);
const ROOT=path.resolve(process.env.DATA_DIR||'./local-data');
const DIRS=Object.fromEntries(['originals','previews','thumbs','renders','exports','masks','ai','tmp','catalogs','galleries','slideshows','books','prints','videos','sidecars','published'].map(k=>[k,path.join(ROOT,k)]));
for(const d of [ROOT,...Object.values(DIRS)]) fs.mkdirSync(d,{recursive:true});
const DB_FILE=path.join(ROOT,'library.json');
const ENGINE=path.resolve('engine/photo_engine.py');
const PY=process.env.PYTHON_BIN||'python3';
const uid=(p='id')=>`${p}_${Date.now().toString(36)}_${crypto.randomBytes(5).toString('hex')}`;
const safeName=(s='file')=>String(s).replace(/[^a-zA-Z0-9._ ()\-]/g,'_').slice(0,180);
const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number(n)||0));
const findPhoto=id=>db.photos.find(p=>p.id===id);
const now=()=>new Date().toISOString();

function defaultEdits(){return {
  profile:{name:'Adobe Color',amount:100,adaptive:false},
  light:{exposure:0,contrast:0,highlights:0,shadows:0,whites:0,blacks:0},
  color:{temperature:0,tint:0,vibrance:0,saturation:0,bw:false,mixer:{red:{hue:0,saturation:0,luminance:0},orange:{hue:0,saturation:0,luminance:0},yellow:{hue:0,saturation:0,luminance:0},green:{hue:0,saturation:0,luminance:0},aqua:{hue:0,saturation:0,luminance:0},blue:{hue:0,saturation:0,luminance:0},purple:{hue:0,saturation:0,luminance:0},magenta:{hue:0,saturation:0,luminance:0}},pointColors:[]},
  curves:{rgb:[[0,0],[1,1]],red:[[0,0],[1,1]],green:[[0,0],[1,1]],blue:[[0,0],[1,1]],refineSaturation:100},
  grading:{shadows:{h:0,s:0,l:0},mids:{h:0,s:0,l:0},highlights:{h:0,s:0,l:0},global:{h:0,s:0,l:0},blending:50,balance:0},
  effects:{texture:0,clarity:0,dehaze:0,vignette:0,vignetteMidpoint:50,vignetteRoundness:0,vignetteFeather:50,vignetteHighlights:0,grain:0,grainSize:25,grainRoughness:50},
  detail:{sharpen:25,radius:1,detail:25,masking:0,luminanceNR:0,luminanceDetail:50,luminanceContrast:0,colorNR:25,colorDetail:50,colorSmoothness:50},
  optics:{chromaticAberration:true,profileCorrections:true,lensMake:'',lensModel:'',lensProfile:'',distortion:0,vignette:0,defringePurple:0,defringeGreen:0},
  geometry:{upright:'off',guides:[],vertical:0,horizontal:0,rotate:0,aspect:0,scale:100,x:0,y:0,constrainCrop:true},
  crop:{ratio:'free',x:0,y:0,width:1,height:1,angle:0,rotate90:0,flipX:false,flipY:false,overlay:'thirds'},
  calibration:{shadowTint:0,redHue:0,redSat:0,greenHue:0,greenSat:0,blueHue:0,blueSat:0},
  masks:[], retouch:[], redEye:[], ai:{lensBlur:null,enhance:null}
};}
function freshDB(){return {schema:6,photos:[],albums:[],albumFolders:[],smartAlbums:[],collectionSets:[],presets:[],metadataPresets:[],exportPresets:[],printPresets:[],books:[],slideshows:[],webGalleries:[],publishServices:[],savedLocations:[],shares:[],communityPosts:[],settings:{createdAt:now(),trashRetentionDays:60,writeXmp:true,autoImportFolder:'',catalogName:'Lumina Catalog'}};}
let db=freshDB();
try{db={...freshDB(),...JSON.parse(fs.readFileSync(DB_FILE,'utf8'))};}catch{fs.writeFileSync(DB_FILE,JSON.stringify(db,null,2));}
let saveQ=Promise.resolve(); const syncClients=new Set(); let revision=0; function broadcastSync(){revision++;const msg=`data: ${JSON.stringify({revision,at:now()})}\n\n`;for(const r of syncClients){try{r.write(msg)}catch{syncClients.delete(r)}}} function saveDB(){saveQ=saveQ.then(async()=>{const t=DB_FILE+'.tmp';await fsp.writeFile(t,JSON.stringify(db,null,2));await fsp.rename(t,DB_FILE);broadcastSync()});return saveQ;}
function normalizeDB(){for(const k of Object.keys(freshDB())) if(db[k]===undefined) db[k]=freshDB()[k]; for(const p of db.photos){p.edits={...defaultEdits(),...(p.edits||{})};p.versions=p.versions||[];p.keywords=p.keywords||[];p.stackId=p.stackId||null;p.deletedAt=p.deletedAt||null;p.virtualCopyOf=p.virtualCopyOf||null;p.gps=p.gps||null;p.ai=p.ai||{};}}
normalizeDB(); saveDB();

app.use(express.json({limit:'50mb'})); app.use(express.static('public',{extensions:['html']}));
const upload=multer({dest:DIRS.tmp,limits:{fileSize:1024*1024*4096}});

function run(cmd,args=[],{timeout=0}={}){return new Promise((resolve,reject)=>{const cp=spawn(cmd,args,{env:process.env});let out='',err='';cp.stdout.on('data',d=>out+=d);cp.stderr.on('data',d=>err+=d);let timer;if(timeout)timer=setTimeout(()=>{cp.kill('SIGKILL');reject(new Error('Process timed out'))},timeout);cp.on('error',reject);cp.on('close',code=>{if(timer)clearTimeout(timer);let parsed;try{parsed=JSON.parse(out.trim().split('\n').at(-1)||'{}')}catch{}if(code===0)resolve(parsed||{ok:true,stdout:out});else reject(new Error(parsed?.error||err||out||`Process exited ${code}`));});});}
async function engine(args,opts={}){return run(PY,[ENGINE,...args],opts)}
async function writeJsonTmp(obj,prefix='payload'){const f=path.join(DIRS.tmp,`${uid(prefix)}.json`);await fsp.writeFile(f,JSON.stringify(obj));return f;}
async function mediaMeta(file){
  const ext=path.extname(file).toLowerCase(); const videoExt=new Set(['.mp4','.mov','.m4v','.mkv','.webm','.avi','.mts','.m2ts']);
  if(videoExt.has(ext)){
    try{const r=spawnSync('ffprobe',['-v','quiet','-print_format','json','-show_format','-show_streams',file],{encoding:'utf8'});const j=JSON.parse(r.stdout||'{}');const v=(j.streams||[]).find(s=>s.codec_type==='video')||{};return {kind:'video',width:v.width||0,height:v.height||0,duration:Number(j.format?.duration||0),codec:v.codec_name||'',format:j.format?.format_name||''};}catch{return {kind:'video',width:0,height:0};}
  }
  try{const m=await sharp(file,{failOn:'none',pages:1}).metadata();let exif={};try{const r=spawnSync('exiftool',['-j','-n',file],{encoding:'utf8',maxBuffer:10*1024*1024});exif=JSON.parse(r.stdout||'[]')[0]||{}}catch{}return {kind:'photo',width:m.width||0,height:m.height||0,format:m.format||ext.slice(1),space:m.space||'',density:m.density||null,orientation:m.orientation||null,pages:m.pages||1,hasAlpha:!!m.hasAlpha,isProgressive:!!m.isProgressive,exif,camera:exif.Model||'',cameraMake:exif.Make||'',lens:exif.LensModel||exif.Lens||'',iso:exif.ISO||null,shutter:exif.ShutterSpeed||exif.ExposureTime||null,aperture:exif.FNumber||exif.Aperture||null,focalLength:exif.FocalLength||null};}
  catch{try{const r=await engine(['metadata','--input',file]);return {kind:'photo',width:r.width||r.visibleWidth||0,height:r.height||r.visibleHeight||0,format:ext.slice(1),raw:!!r.raw,exif:r.exif||{}}}catch{return {kind:'photo',width:0,height:0,format:ext.slice(1)}}}
}
async function buildPreview(file,id,meta){
  const prev=path.join(DIRS.previews,`${id}.jpg`),thumb=path.join(DIRS.thumbs,`${id}.jpg`);
  if(meta.kind==='video'){
    await run('ffmpeg',['-y','-ss','0','-i',file,'-frames:v','1','-vf','scale=1800:1800:force_original_aspect_ratio=decrease',prev]).catch(()=>{});
    if(fs.existsSync(prev)) await sharp(prev).resize({width:420,height:420,fit:'cover'}).jpeg({quality:82}).toFile(thumb); return;
  }
  try{await sharp(file,{failOn:'none'}).rotate().resize({width:1800,height:1800,fit:'inside',withoutEnlargement:true}).jpeg({quality:90,mozjpeg:true}).toFile(prev);await sharp(file,{failOn:'none'}).rotate().resize({width:420,height:420,fit:'cover'}).jpeg({quality:82}).toFile(thumb);}
  catch{const edits=await writeJsonTmp(defaultEdits(),'edits');const opts=await writeJsonTmp({quality:90},'opts');await engine(['render','--input',file,'--output',prev,'--edits',edits,'--options',opts,'--max-dim','1800'],{timeout:120000});await sharp(prev).resize({width:420,height:420,fit:'cover'}).jpeg({quality:82}).toFile(thumb);await Promise.all([fsp.unlink(edits).catch(()=>{}),fsp.unlink(opts).catch(()=>{})]);}
}
async function sidecar(p){if(!db.settings.writeXmp||p.meta?.kind==='video')return;const xmp=`<?xpacket begin="﻿"?><x:xmpmeta xmlns:x="adobe:ns:meta/"><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"><rdf:Description xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:xmp="http://ns.adobe.com/xap/1.0/" xmp:Rating="${p.rating||0}"><dc:title><rdf:Alt><rdf:li xml:lang="x-default">${String(p.title||'').replaceAll('&','&amp;')}</rdf:li></rdf:Alt></dc:title><dc:description><rdf:Alt><rdf:li xml:lang="x-default">${String(p.caption||'').replaceAll('&','&amp;')}</rdf:li></rdf:Alt></dc:description><dc:subject><rdf:Bag>${(p.keywords||[]).map(k=>`<rdf:li>${String(k).replaceAll('&','&amp;')}</rdf:li>`).join('')}</rdf:Bag></dc:subject></rdf:Description></rdf:RDF></x:xmpmeta><?xpacket end="w"?>`;await fsp.writeFile(path.join(DIRS.sidecars,`${p.id}.xmp`),xmp).catch(()=>{});}
function visiblePhotos(){return db.photos.filter(p=>!p.deletedAt)}function capturedFromMeta(meta){const x=meta?.exif||{},v=x.DateTimeOriginal||x.CreateDate;if(!v)return now();const m=String(v).match(/(\d{4}):(\d{2}):(\d{2})[ T](\d{2}):(\d{2}):(\d{2})/);return m?new Date(`${m[1]}-${m[2]}-${m[3]}T${m[4]}:${m[5]}:${m[6]}`).toISOString():now()}function gpsFromMeta(meta){const x=meta?.exif||{};return Number.isFinite(Number(x.GPSLatitude))&&Number.isFinite(Number(x.GPSLongitude))?{lat:Number(x.GPSLatitude),lon:Number(x.GPSLongitude)}:null;}
async function purgeTrash(){const days=Number(db.settings.trashRetentionDays||60),cut=Date.now()-days*86400000;const doomed=db.photos.filter(p=>p.deletedAt&&new Date(p.deletedAt).getTime()<cut);for(const p of doomed)await hardDelete(p);if(doomed.length)await saveDB();}
async function hardDelete(p){db.photos=db.photos.filter(x=>x.id!==p.id);db.albums.forEach(a=>a.photoIds=(a.photoIds||[]).filter(id=>id!==p.id));for(const d of Object.values(DIRS)){const names=await fsp.readdir(d).catch(()=>[]);await Promise.all(names.filter(n=>n.startsWith(p.id)).map(n=>fsp.rm(path.join(d,n),{force:true,recursive:true}).catch(()=>{})));}}
setInterval(()=>purgeTrash().catch(()=>{}),6*3600*1000).unref(); purgeTrash().catch(()=>{});

app.get('/api/health',(_q,res)=>res.json({ok:true,dataDir:ROOT,photos:visiblePhotos().length,python:spawnSync(PY,['--version'],{encoding:'utf8'}).stdout||'available'}));
app.get('/api/state',(_q,res)=>res.json({...db,photos:visiblePhotos()}));
app.get('/api/trash',(_q,res)=>res.json(db.photos.filter(p=>p.deletedAt)));
app.get('/api/capabilities',(_q,res)=>res.json({raw:true,hdr:true,panorama:true,video:true,localAI:true,tethering:true,print:true,books:true,slideshows:true,webGallery:true,catalogs:true,excluded:['generative-expand','ai-search','image-to-video']}));
app.get('/api/events',(req,res)=>{res.setHeader('Content-Type','text/event-stream');res.setHeader('Cache-Control','no-cache');res.setHeader('Connection','keep-alive');res.flushHeaders?.();syncClients.add(res);res.write(`data: ${JSON.stringify({revision,at:now()})}\n\n`);req.on('close',()=>syncClients.delete(res));});


app.post('/api/photos',upload.array('photos',300),async(req,res)=>{const items=[];for(const f of req.files||[]){const id=uid('ph'),ext=path.extname(f.originalname).toLowerCase()||'.bin',dest=path.join(DIRS.originals,`${id}${ext}`);try{await fsp.rename(f.path,dest);const meta=await mediaMeta(dest);await buildPreview(dest,id,meta);const t=now();const p={id,name:safeName(f.originalname),ext,originalPath:path.basename(dest),importedAt:t,modifiedAt:t,capturedAt:capturedFromMeta(meta),rating:0,flag:'none',colorLabel:'',customLabels:[],favorite:false,keywords:[],title:'',caption:'',copyright:'',creator:'',location:'',gps:gpsFromMeta(meta),meta,edits:defaultEdits(),versions:[],stackId:null,stackOrder:0,virtualCopyOf:null,deletedAt:null,ai:{status:'ready',artifacts:[]}};db.photos.unshift(p);items.push(p);await sidecar(p);}catch(e){items.push({error:e.message,name:f.originalname});await fsp.rm(f.path,{force:true}).catch(()=>{})}}await saveDB();res.json({items});});
app.patch('/api/photos/:id',async(req,res)=>{const p=findPhoto(req.params.id);if(!p)return res.status(404).json({error:'Photo not found'});const allowed=['rating','flag','colorLabel','customLabels','favorite','keywords','title','caption','copyright','creator','location','gps','capturedAt','edits','name','ai','stackId','stackOrder'];for(const k of allowed)if(k in req.body)p[k]=req.body[k];p.modifiedAt=now();await Promise.all([saveDB(),sidecar(p)]);res.json(p);});
app.post('/api/photos/batch',async(req,res)=>{const ids=req.body.ids||[],fields=req.body.fields||{};const out=[];for(const id of ids){const p=findPhoto(id);if(!p)continue;for(const [k,v] of Object.entries(fields))if(['rating','flag','colorLabel','favorite','keywords','copyright','creator','location'].includes(k))p[k]=v;p.modifiedAt=now();out.push(p);await sidecar(p);}await saveDB();res.json({items:out});});
app.delete('/api/photos/:id',async(req,res)=>{const p=findPhoto(req.params.id);if(!p)return res.status(404).json({error:'Photo not found'});p.deletedAt=now();await saveDB();res.json({ok:true,softDeleted:true});});
app.post('/api/photos/:id/restore',async(req,res)=>{const p=findPhoto(req.params.id);if(!p)return res.status(404).json({error:'Photo not found'});p.deletedAt=null;await saveDB();res.json(p);});
app.delete('/api/photos/:id/permanent',async(req,res)=>{const p=findPhoto(req.params.id);if(!p)return res.status(404).json({error:'Photo not found'});await hardDelete(p);await saveDB();res.json({ok:true});});
app.post('/api/photos/:id/virtual-copy',async(req,res)=>{const p=findPhoto(req.params.id);if(!p)return res.status(404).json({error:'Photo not found'});const c=structuredClone(p);c.id=uid('ph');c.name=`${path.parse(p.name).name} Copy${p.ext}`;c.virtualCopyOf=p.virtualCopyOf||p.id;c.versions=[];c.importedAt=now();c.modifiedAt=now();c.deletedAt=null;db.photos.unshift(c);await saveDB();res.json(c);});
app.post('/api/photos/auto-stack',async(req,res)=>{const seconds=Math.max(1,Number(req.body.seconds||10));const items=(req.body.ids?.map(findPhoto).filter(Boolean)||visiblePhotos()).sort((a,b)=>new Date(a.capturedAt)-new Date(b.capturedAt));let group=[];const flush=()=>{if(group.length>1){const sid=uid('stack');group.forEach((p,i)=>{p.stackId=sid;p.stackOrder=i})}group=[]};for(const p of items){if(!group.length||Math.abs(new Date(p.capturedAt)-new Date(group.at(-1).capturedAt))/1000<=seconds)group.push(p);else{flush();group=[p]}}flush();await saveDB();res.json({ok:true});});

app.get('/media/:kind/:file',(req,res)=>{const d=({original:DIRS.originals,preview:DIRS.previews,thumb:DIRS.thumbs,render:DIRS.renders,export:DIRS.exports,ai:DIRS.ai,gallery:DIRS.galleries,slideshow:DIRS.slideshows,book:DIRS.books,print:DIRS.prints,video:DIRS.videos,published:DIRS.published})[req.params.kind];if(!d)return res.sendStatus(404);res.sendFile(path.join(d,path.basename(req.params.file)));});

app.post('/api/albums',async(req,res)=>{const a={id:uid('al'),name:String(req.body.name||'New Album').slice(0,100),folderId:req.body.folderId||null,photoIds:[],createdAt:now(),sort:'custom'};db.albums.push(a);await saveDB();res.json(a)});
app.patch('/api/albums/:id',async(req,res)=>{const a=db.albums.find(x=>x.id===req.params.id);if(!a)return res.status(404).json({error:'Album not found'});for(const k of ['name','folderId','sort'])if(k in req.body)a[k]=req.body[k];if(Array.isArray(req.body.photoIds))a.photoIds=[...new Set(req.body.photoIds.filter(id=>findPhoto(id)))];await saveDB();res.json(a)});
app.delete('/api/albums/:id',async(req,res)=>{db.albums=db.albums.filter(a=>a.id!==req.params.id);await saveDB();res.json({ok:true})});
app.post('/api/album-folders',async(req,res)=>{const x={id:uid('folder'),name:String(req.body.name||'Folder'),parentId:req.body.parentId||null};db.albumFolders.push(x);await saveDB();res.json(x)});
app.post('/api/smart-albums',async(req,res)=>{const x={id:uid('smart'),name:String(req.body.name||'Smart Album'),match:req.body.match==='any'?'any':'all',rules:req.body.rules||[],createdAt:now()};db.smartAlbums.push(x);await saveDB();res.json(x)});
app.get('/api/smart-albums/:id/photos',(req,res)=>{const s=db.smartAlbums.find(x=>x.id===req.params.id);if(!s)return res.status(404).json({error:'Not found'});const test=(p,r)=>{const v=p[r.field];if(r.op==='eq')return v==r.value;if(r.op==='neq')return v!=r.value;if(r.op==='gte')return Number(v)>=Number(r.value);if(r.op==='lte')return Number(v)<=Number(r.value);if(r.op==='contains')return String(Array.isArray(v)?v.join(' '):v||'').toLowerCase().includes(String(r.value).toLowerCase());return true};res.json(visiblePhotos().filter(p=>s.match==='any'?s.rules.some(r=>test(p,r)):s.rules.every(r=>test(p,r)))) });

app.post('/api/photos/:id/versions',async(req,res)=>{const p=findPhoto(req.params.id);if(!p)return res.status(404).json({error:'Photo not found'});const v={id:uid('ver'),name:String(req.body.name||`Version ${p.versions.length+1}`),createdAt:now(),edits:structuredClone(p.edits)};p.versions.unshift(v);await saveDB();res.json(v)});
app.post('/api/photos/:id/versions/:vid/restore',async(req,res)=>{const p=findPhoto(req.params.id),v=p?.versions.find(x=>x.id===req.params.vid);if(!v)return res.status(404).json({error:'Version not found'});p.edits=structuredClone(v.edits);p.modifiedAt=now();await saveDB();res.json(p)});
app.post('/api/presets',async(req,res)=>{const x={id:uid('pre'),name:String(req.body.name||'Preset'),group:req.body.group||'User Presets',amount:100,edits:req.body.edits||defaultEdits(),createdAt:now(),adaptive:!!req.body.adaptive};db.presets.unshift(x);await saveDB();res.json(x)});
app.delete('/api/presets/:id',async(req,res)=>{db.presets=db.presets.filter(x=>x.id!==req.params.id);await saveDB();res.json({ok:true})});
app.get('/api/presets/:id/xmp',(req,res)=>{const x=db.presets.find(p=>p.id===req.params.id);if(!x)return res.sendStatus(404);const body=`<x:xmpmeta xmlns:x="adobe:ns:meta/"><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"><rdf:Description xmlns:lumina="https://lumina.local/" lumina:Name="${x.name}"><lumina:Edits>${Buffer.from(JSON.stringify(x.edits)).toString('base64')}</lumina:Edits></rdf:Description></rdf:RDF></x:xmpmeta>`;res.type('application/rdf+xml').attachment(`${safeName(x.name)}.xmp`).send(body)});

app.get('/api/photos/:id/render',async(req,res,next)=>{try{const p=findPhoto(req.params.id);if(!p)return res.sendStatus(404);const key=crypto.createHash('sha1').update(JSON.stringify(p.edits)+String(req.query.max||1800)).digest('hex').slice(0,12);const out=path.join(DIRS.renders,`${p.id}-${key}.jpg`);if(!fs.existsSync(out)){const ef=await writeJsonTmp(p.edits,'edits'),of=await writeJsonTmp({quality:90,maxSize:Number(req.query.max||1800)},'opts');await engine(['render','--input',path.join(DIRS.originals,p.originalPath),'--output',out,'--edits',ef,'--options',of,'--max-dim',String(Number(req.query.max||2200))],{timeout:180000});fsp.rm(ef,{force:true});fsp.rm(of,{force:true});}res.sendFile(out)}catch(e){next(e)}});
app.post('/api/photos/:id/export',async(req,res)=>{const p=findPhoto(req.params.id);if(!p)return res.status(404).json({error:'Photo not found'});const fmt=String(req.body.format||'jpeg').toLowerCase();const ext=({jpeg:'jpg',jpg:'jpg',png:'png',webp:'webp',tiff:'tiff',avif:'avif'})[fmt]||'jpg';const filename=`${safeName(path.parse(p.name).name)}-edited-${Date.now()}.${ext}`,out=path.join(DIRS.exports,filename);const ef=await writeJsonTmp(p.edits,'edits'),of=await writeJsonTmp(req.body,'opts');try{await engine(['render','--input',path.join(DIRS.originals,p.originalPath),'--output',out,'--edits',ef,'--options',of],{timeout:600000});res.json({url:`/media/export/${encodeURIComponent(filename)}`,filename})}finally{fsp.rm(ef,{force:true});fsp.rm(of,{force:true})}});
app.post('/api/export/batch',async(req,res)=>{const ids=req.body.ids||[];const files=[];for(const id of ids){const p=findPhoto(id);if(!p)continue;const x=await new Promise((resolve,reject)=>{const fmt=String(req.body.format||'jpeg').toLowerCase(),ext=fmt==='jpeg'?'jpg':fmt,filename=`${safeName(path.parse(p.name).name)}-${Date.now()}.${ext}`,out=path.join(DIRS.exports,filename);Promise.all([writeJsonTmp(p.edits,'e'),writeJsonTmp(req.body,'o')]).then(async([ef,of])=>{try{await engine(['render','--input',path.join(DIRS.originals,p.originalPath),'--output',out,'--edits',ef,'--options',of],{timeout:600000});resolve({filename,url:`/media/export/${encodeURIComponent(filename)}`})}catch(e){reject(e)}finally{fsp.rm(ef,{force:true});fsp.rm(of,{force:true})}})});files.push(x)}res.json({files})});

async function importGenerated(file,name){const id=uid('ph'),ext=path.extname(file)||'.jpg',dest=path.join(DIRS.originals,`${id}${ext}`);await fsp.copyFile(file,dest);const meta=await mediaMeta(dest);await buildPreview(dest,id,meta);const p={id,name:safeName(name),ext,originalPath:path.basename(dest),importedAt:now(),modifiedAt:now(),capturedAt:capturedFromMeta(meta),rating:0,flag:'none',colorLabel:'',favorite:false,keywords:[],title:'',caption:'',copyright:'',meta,edits:defaultEdits(),versions:[],deletedAt:null,ai:{artifacts:[]}};db.photos.unshift(p);await saveDB();return p;}
app.post('/api/merge/hdr',async(req,res)=>{const ps=(req.body.ids||[]).map(findPhoto).filter(Boolean);if(ps.length<2)return res.status(400).json({error:'Select at least two photos'});const out=path.join(DIRS.tmp,`${uid('hdr')}.jpg`);await engine(['hdr','--inputs',...ps.map(p=>path.join(DIRS.originals,p.originalPath)),'--output',out],{timeout:600000});const p=await importGenerated(out,req.body.name||'HDR Merge.jpg');fsp.rm(out,{force:true});res.json(p)});
app.post('/api/merge/panorama',async(req,res)=>{const ps=(req.body.ids||[]).map(findPhoto).filter(Boolean);if(ps.length<2)return res.status(400).json({error:'Select at least two photos'});const out=path.join(DIRS.tmp,`${uid('pano')}.jpg`);await engine(['panorama','--inputs',...ps.map(p=>path.join(DIRS.originals,p.originalPath)),'--output',out],{timeout:600000});const p=await importGenerated(out,req.body.name||'Panorama.jpg');fsp.rm(out,{force:true});res.json(p)});
app.post('/api/merge/hdr-panorama',async(req,res)=>{try{const groups=req.body.groups||[];if(groups.length<2)return res.status(400).json({error:'Provide at least two bracket groups'});const merged=[];for(const group of groups){const ps=group.map(findPhoto).filter(Boolean);if(ps.length<2)continue;const tmp=path.join(DIRS.tmp,`${uid('hdrpart')}.jpg`);await engine(['hdr','--inputs',...ps.map(p=>path.join(DIRS.originals,p.originalPath)),'--output',tmp],{timeout:600000});merged.push(tmp)}if(merged.length<2)return res.status(400).json({error:'Not enough valid HDR groups'});const out=path.join(DIRS.tmp,`${uid('hdrpano')}.jpg`);await engine(['panorama','--inputs',...merged,'--output',out],{timeout:900000});const photo=await importGenerated(out,req.body.name||'HDR Panorama.jpg');await Promise.all([...merged,out].map(f=>fsp.rm(f,{force:true})));res.json(photo)}catch(e){res.status(500).json({error:e.message})}});

const AI_ALLOWED=new Set(['subject-mask','sky-mask','background-mask','object-mask','people-mask','landscape-mask','lens-blur-depth','denoise','raw-details','super-resolution','generative-remove','distraction-people','distraction-reflections','distraction-dust','blemish-retouch','assisted-culling','recommended-presets','adaptive-presets','adaptive-profiles','auto-light-color','ai-sharpen']);
app.get('/api/ai/capabilities',(_q,res)=>res.json({architecture:'local-heavyweight',features:[...AI_ALLOWED],excluded:['generative-expand','ai-search','image-to-video'],models:{segmentation:process.env.LUMINA_SEGMENT_MODEL||'nvidia/segformer-b5-finetuned-ade-640-640',objects:process.env.LUMINA_OBJECT_MODEL||'facebook/mask2former-swin-large-coco-panoptic',depth:process.env.LUMINA_DEPTH_MODEL||'depth-anything/Depth-Anything-V2-Small-hf',superResolution:process.env.LUMINA_SR_MODEL||'caidas/swin2SR-classical-sr-x2-64',inpainting:process.env.LUMINA_INPAINT_MODEL||'diffusers/stable-diffusion-xl-1.0-inpainting-0.1'}}));
app.post('/api/ai/run',async(req,res)=>{try{const feature=String(req.body.feature||'');if(!AI_ALLOWED.has(feature))return res.status(400).json({error:'Unsupported or intentionally excluded feature'});const p=findPhoto(req.body.photoId);if(!p&&feature!=='assisted-culling')return res.status(404).json({error:'Photo not found'});const input=p?path.join(DIRS.originals,p.originalPath):path.join(DIRS.previews,`${req.body.ids?.[0]}.jpg`);let ext=['subject-mask','sky-mask','background-mask','object-mask','people-mask','landscape-mask'].includes(feature)?'.png':'.jpg';const out=path.join(DIRS.ai,`${p?.id||'batch'}-${feature}-${Date.now()}${ext}`);const payload={...req.body,inputs:(req.body.ids||[]).map(id=>{const q=findPhoto(id);return q?path.join(DIRS.originals,q.originalPath):null}).filter(Boolean)};if(req.body.maskDataUrl){const b=Buffer.from(req.body.maskDataUrl.split(',').at(-1),'base64'),mf=path.join(DIRS.tmp,`${uid('mask')}.png`);await fsp.writeFile(mf,b);payload.maskPath=mf;}const pf=await writeJsonTmp(payload,'ai');const result=await engine(['ai','--feature',feature,'--input',input,'--output',out,'--payload',pf],{timeout:1800000});fsp.rm(pf,{force:true});if(payload.maskPath)fsp.rm(payload.maskPath,{force:true});if(p&&result.output){p.ai=p.ai||{artifacts:[]};p.ai.artifacts=p.ai.artifacts||[];p.ai.artifacts.unshift({feature,file:path.basename(result.output),createdAt:now()});p.modifiedAt=now();await saveDB();}const conv={...result};if(result.output)conv.url=`/media/ai/${encodeURIComponent(path.basename(result.output))}`;if(result.mask)conv.maskUrl=`/media/ai/${encodeURIComponent(path.basename(result.mask))}`;const maskFeatures=new Set(['subject-mask','sky-mask','background-mask','object-mask','people-mask','landscape-mask']);const editOnly=new Set(['auto-light-color','recommended-presets','adaptive-presets','adaptive-profiles','assisted-culling']);if(p&&result.output&&!maskFeatures.has(feature)&&!editOnly.has(feature)){const generated=await importGenerated(result.output,`${path.parse(p.name).name}-${feature}.jpg`);generated.aiParent=p.id;generated.aiSourceFeature=feature;await saveDB();conv.generatedPhoto=generated;}res.json(conv);}catch(e){res.status(500).json({error:e.message})}});

app.post('/api/video/:id/export',async(req,res)=>{const p=findPhoto(req.params.id);if(!p||p.meta?.kind!=='video')return res.status(400).json({error:'Video not found'});const out=path.join(DIRS.videos,`${safeName(path.parse(p.name).name)}-${Date.now()}.mp4`),of=await writeJsonTmp(req.body,'video');try{await engine(['video','--input',path.join(DIRS.originals,p.originalPath),'--output',out,'--options',of],{timeout:1800000});res.json({filename:path.basename(out),url:`/media/video/${encodeURIComponent(path.basename(out))}`})}finally{fsp.rm(of,{force:true})}});
app.get('/api/video/:id/frame',async(req,res)=>{const p=findPhoto(req.params.id);if(!p)return res.sendStatus(404);const out=path.join(DIRS.tmp,`${uid('frame')}.jpg`);await run('ffmpeg',['-y','-ss',String(req.query.time||0),'-i',path.join(DIRS.originals,p.originalPath),'-frames:v','1',out]);res.sendFile(out,()=>fsp.rm(out,{force:true}))});

app.post('/api/galleries',async(req,res)=>{const id=uid('gallery'),title=String(req.body.title||'Gallery'),ps=(req.body.ids||[]).map(findPhoto).filter(Boolean),items=ps.map(p=>({src:`../previews/${p.id}.jpg`,caption:p.caption||p.title||p.name})),payload=await writeJsonTmp({title,items},'gallery'),out=path.join(DIRS.galleries,`${id}.html`);await engine(['gallery','--payload',payload,'--output',out]);fsp.rm(payload,{force:true});const g={id,title,photoIds:ps.map(p=>p.id),createdAt:now(),file:path.basename(out)};db.webGalleries.push(g);await saveDB();res.json({...g,url:`/media/gallery/${g.file}`})});
app.post('/api/slideshows',async(req,res)=>{const ps=(req.body.ids||[]).map(findPhoto).filter(Boolean);if(!ps.length)return res.status(400).json({error:'No photos'});const id=uid('show'),work=path.join(DIRS.tmp,id);await fsp.mkdir(work,{recursive:true});const duration=Math.max(.5,Number(req.body.duration||3));let concat='';let i=0;for(const p of ps){const img=path.join(DIRS.previews,`${p.id}.jpg`);const cp=path.join(work,`${String(i++).padStart(4,'0')}.jpg`);await fsp.copyFile(img,cp);concat+=`file '${cp.replaceAll("'","'\\''")}'\nduration ${duration}\n`;}const cf=path.join(work,'list.txt');await fsp.writeFile(cf,concat);const out=path.join(DIRS.slideshows,`${id}.mp4`);const args=['-y','-f','concat','-safe','0','-i',cf,'-vf','scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2,format=yuv420p','-r','30','-c:v','libx264','-pix_fmt','yuv420p'];if(req.body.musicPath&&fs.existsSync(req.body.musicPath))args.push('-i',req.body.musicPath,'-shortest','-c:a','aac');args.push(out);await run('ffmpeg',args,{timeout:1800000});await fsp.rm(work,{recursive:true,force:true});const s={id,name:req.body.name||'Slideshow',photoIds:ps.map(p=>p.id),file:path.basename(out),createdAt:now(),duration,crossfade:req.body.crossfade||1};db.slideshows.push(s);await saveDB();res.json({...s,url:`/media/slideshow/${s.file}`})});

app.post('/api/books',async(req,res)=>{const ps=(req.body.ids||[]).map(findPhoto).filter(Boolean);const id=uid('book'),out=path.join(DIRS.books,`${id}.pdf`),spec={title:req.body.title||'Photo Book',pageSize:req.body.pageSize||'letter',images:ps.map(p=>path.join(DIRS.previews,`${p.id}.jpg`)),captions:ps.map(p=>p.caption||p.title||p.name)};const sf=await writeJsonTmp(spec,'book');await run(PY,['-c',`import json,sys;from reportlab.pdfgen import canvas;from reportlab.lib.pagesizes import letter,A4;from reportlab.lib.utils import ImageReader;s=json.load(open(sys.argv[1]));o=sys.argv[2];size=A4 if s.get('pageSize')=='a4' else letter;c=canvas.Canvas(o,pagesize=size);W,H=size;c.setFont('Helvetica-Bold',22);c.drawString(40,H-50,s.get('title','Photo Book'));c.showPage();\nfor i,p in enumerate(s['images']):\n im=ImageReader(p); iw,ih=im.getSize(); sc=min((W-60)/iw,(H-100)/ih); w,h=iw*sc,ih*sc;c.drawImage(im,(W-w)/2,(H-h)/2+20,w,h,preserveAspectRatio=True);c.setFont('Helvetica',10);c.drawCentredString(W/2,25,s['captions'][i][:110]);c.showPage()\nc.save()`,sf,out],{timeout:300000});fsp.rm(sf,{force:true});const b={id,title:spec.title,photoIds:ps.map(p=>p.id),file:path.basename(out),createdAt:now()};db.books.push(b);await saveDB();res.json({...b,url:`/media/book/${b.file}`})});
app.post('/api/print',async(req,res)=>{const ps=(req.body.ids||[]).map(findPhoto).filter(Boolean);const id=uid('print'),out=path.join(DIRS.prints,`${id}.pdf`),spec={title:req.body.title||'Print Sheet',images:ps.map(p=>path.join(DIRS.previews,`${p.id}.jpg`)),columns:Number(req.body.columns||3),rows:Number(req.body.rows||4),border:Number(req.body.border||8)};const sf=await writeJsonTmp(spec,'print');await run(PY,['-c',`import json,sys,math;from reportlab.pdfgen import canvas;from reportlab.lib.pagesizes import letter;from reportlab.lib.utils import ImageReader;s=json.load(open(sys.argv[1]));c=canvas.Canvas(sys.argv[2],pagesize=letter);W,H=letter;cols,rows=s['columns'],s['rows'];cw,ch=W/cols,H/rows;b=s['border'];\nfor i,p in enumerate(s['images']):\n j=i%(cols*rows);\n if j==0 and i:c.showPage();\n col=j%cols;row=j//cols;im=ImageReader(p);iw,ih=im.getSize();sc=min((cw-2*b)/iw,(ch-2*b)/ih);w,h=iw*sc,ih*sc;x=col*cw+(cw-w)/2;y=H-(row+1)*ch+(ch-h)/2;c.drawImage(im,x,y,w,h,preserveAspectRatio=True)\nc.save()`,sf,out]);fsp.rm(sf,{force:true});res.json({id,file:path.basename(out),url:`/media/print/${path.basename(out)}`})});

app.post('/api/map/gpx',upload.single('gpx'),async(req,res)=>{const text=await fsp.readFile(req.file.path,'utf8');await fsp.rm(req.file.path,{force:true});const pts=[...text.matchAll(/<trkpt[^>]*lat="([^"]+)"[^>]*lon="([^"]+)"[^>]*>[\s\S]*?<time>([^<]+)<\/time>/g)].map(m=>({lat:+m[1],lon:+m[2],time:new Date(m[3]).getTime()}));let matched=0;for(const p of visiblePhotos()){const t=new Date(p.capturedAt).getTime();let best=null,delta=Infinity;for(const q of pts){const d=Math.abs(q.time-t);if(d<delta){delta=d;best=q}}if(best&&delta<5*60*1000){p.gps={lat:best.lat,lon:best.lon};matched++}}await saveDB();res.json({points:pts.length,matched})});
app.post('/api/map/locations',async(req,res)=>{const x={id:uid('loc'),name:String(req.body.name||'Location'),lat:Number(req.body.lat),lon:Number(req.body.lon),radius:Number(req.body.radius||100),private:!!req.body.private};db.savedLocations.push(x);await saveDB();res.json(x)});

app.post('/api/catalog/export',async(req,res)=>{const filename=`catalog-${Date.now()}.zip`,out=path.join(DIRS.catalogs,filename);const output=fs.createWriteStream(out),ar=archiver('zip',{zlib:{level:7}});ar.pipe(output);ar.append(JSON.stringify(db,null,2),{name:'library.json'});if(req.body.includeOriginals)for(const p of visiblePhotos())ar.file(path.join(DIRS.originals,p.originalPath),{name:`originals/${p.originalPath}`});if(req.body.includePreviews)for(const p of visiblePhotos())ar.file(path.join(DIRS.previews,`${p.id}.jpg`),{name:`previews/${p.id}.jpg`});await ar.finalize();await new Promise((resolve,reject)=>{output.on('close',resolve);output.on('error',reject)});res.json({filename,url:`/api/catalog/download/${encodeURIComponent(filename)}`})});
app.get('/api/catalog/download/:file',(req,res)=>res.download(path.join(DIRS.catalogs,path.basename(req.params.file))));

app.post('/api/publish',async(req,res)=>{const name=safeName(req.body.name||'Published'),dir=path.join(DIRS.published,`${name}-${Date.now()}`);await fsp.mkdir(dir,{recursive:true});const ids=req.body.ids||[];for(const id of ids){const p=findPhoto(id);if(!p)continue;await fsp.copyFile(path.join(DIRS.previews,`${p.id}.jpg`),path.join(dir,`${safeName(path.parse(p.name).name)}.jpg`))}const svc={id:uid('pub'),name,kind:'hard-drive',path:dir,photoIds:ids,createdAt:now()};db.publishServices.push(svc);await saveDB();res.json(svc)});

app.post('/api/tether/capture',async(req,res)=>{const name=`tether-${Date.now()}.jpg`,tmp=path.join(DIRS.tmp,name);try{await run('gphoto2',['--capture-image-and-download','--filename',tmp],{timeout:120000});const p=await importGenerated(tmp,name);await fsp.rm(tmp,{force:true});res.json(p)}catch(e){res.status(500).json({error:`Tether capture failed: ${e.message}`})}});
app.get('/api/tether/cameras',async(_req,res)=>{try{const r=await run('gphoto2',['--auto-detect']);res.json({raw:r.stdout||'',available:true})}catch(e){res.json({available:false,error:e.message})}});


// Sharing, collaboration, comments, likes, and contribution uploads.
app.post('/api/share/album/:id',async(req,res)=>{const a=db.albums.find(x=>x.id===req.params.id);if(!a)return res.status(404).json({error:'Album not found'});const token=crypto.randomBytes(18).toString('base64url');const sh={id:uid('share'),token,albumId:a.id,createdAt:now(),allowDownload:req.body.allowDownload!==false,allowContribute:!!req.body.allowContribute,allowEdit:!!req.body.allowEdit,comments:[],likes:0};db.shares.push(sh);await saveDB();res.json({...sh,url:`/share.html?token=${token}`})});
app.get('/api/share/:token',(req,res)=>{const sh=db.shares.find(x=>x.token===req.params.token);if(!sh)return res.status(404).json({error:'Share not found'});const a=db.albums.find(x=>x.id===sh.albumId);const photos=(a?.photoIds||[]).map(findPhoto).filter(p=>p&&!p.deletedAt).map(p=>({id:p.id,name:p.name,title:p.title,caption:p.caption,rating:p.rating,preview:`/media/preview/${p.id}.jpg`,original:sh.allowDownload?`/media/original/${encodeURIComponent(p.originalPath)}`:null}));res.json({share:{...sh,token:undefined},album:{id:a?.id,name:a?.name},photos})});
app.post('/api/share/:token/comment',async(req,res)=>{const sh=db.shares.find(x=>x.token===req.params.token);if(!sh)return res.status(404).json({error:'Share not found'});const c={id:uid('comment'),name:String(req.body.name||'Guest').slice(0,60),text:String(req.body.text||'').slice(0,2000),photoId:req.body.photoId||null,createdAt:now()};sh.comments.push(c);await saveDB();res.json(c)});
app.post('/api/share/:token/like',async(req,res)=>{const sh=db.shares.find(x=>x.token===req.params.token);if(!sh)return res.status(404).json({error:'Share not found'});sh.likes=(sh.likes||0)+1;await saveDB();res.json({likes:sh.likes})});
app.post('/api/share/:token/contribute',upload.array('photos',50),async(req,res)=>{const sh=db.shares.find(x=>x.token===req.params.token);if(!sh?.allowContribute)return res.status(403).json({error:'Contributions disabled'});const a=db.albums.find(x=>x.id===sh.albumId);const added=[];for(const f of req.files||[]){const id=uid('ph'),ext=path.extname(f.originalname).toLowerCase()||'.jpg',dest=path.join(DIRS.originals,`${id}${ext}`);await fsp.rename(f.path,dest);const meta=await mediaMeta(dest);await buildPreview(dest,id,meta);const p={id,name:safeName(f.originalname),ext,originalPath:path.basename(dest),importedAt:now(),modifiedAt:now(),capturedAt:capturedFromMeta(meta),rating:0,flag:'none',colorLabel:'',favorite:false,keywords:[],title:'',caption:'',copyright:'',meta,edits:defaultEdits(),versions:[],deletedAt:null,ai:{artifacts:[]}};db.photos.unshift(p);a.photoIds.push(id);added.push(p)}await saveDB();res.json({items:added})});
app.patch('/api/share/:token/photos/:id',async(req,res)=>{const sh=db.shares.find(x=>x.token===req.params.token);if(!sh?.allowEdit)return res.status(403).json({error:'Collaborative editing disabled'});const a=db.albums.find(x=>x.id===sh.albumId),p=findPhoto(req.params.id);if(!p||!a?.photoIds.includes(p.id))return res.status(404).json({error:'Photo not in shared album'});if(req.body.edits)p.edits=req.body.edits;if('title'in req.body)p.title=req.body.title;if('caption'in req.body)p.caption=req.body.caption;p.modifiedAt=now();await saveDB();res.json(p)});

// Local Discover/remix community. This intentionally stays inside the user's own deployment.
app.get('/api/community',(_req,res)=>res.json(db.communityPosts.slice().reverse()));
app.post('/api/community',async(req,res)=>{const p=findPhoto(req.body.photoId);if(!p)return res.status(404).json({error:'Photo not found'});const post={id:uid('post'),photoId:p.id,name:p.name,author:String(req.body.author||'Local Creator').slice(0,80),caption:String(req.body.caption||p.caption||'').slice(0,1000),createdAt:now(),preview:`/media/preview/${p.id}.jpg`,edits:structuredClone(p.edits),likes:0};db.communityPosts.push(post);await saveDB();res.json(post)});
app.post('/api/community/:id/like',async(req,res)=>{const x=db.communityPosts.find(x=>x.id===req.params.id);if(!x)return res.sendStatus(404);x.likes=(x.likes||0)+1;await saveDB();res.json({likes:x.likes})});
app.post('/api/community/:id/remix',async(req,res)=>{const x=db.communityPosts.find(x=>x.id===req.params.id),p=findPhoto(req.body.photoId);if(!x||!p)return res.status(404).json({error:'Post or target photo not found'});p.edits=structuredClone(x.edits);p.modifiedAt=now();await saveDB();res.json(p)});
app.get('/api/tutorials',(_req,res)=>res.json([{id:'light',title:'Light and tone',steps:['Set Exposure for overall brightness','Recover Highlights and open Shadows','Set Whites and Blacks for endpoints','Fine tune with the Tone Curve']},{id:'color',title:'Color workflow',steps:['Set white balance','Use Vibrance before Saturation','Target colors with Color Mixer and Point Color','Finish with Color Grading']},{id:'masking',title:'Local masking',steps:['Choose Subject, Sky, Brush, Linear, Radial, or a range mask','Add local Light/Color/Effects adjustments','Invert or combine masks','Review at 100%']}]));

// External editor handoff: creates a full-resolution TIFF that another app can modify, then normal Import brings it back.
app.post('/api/photos/:id/external-copy',async(req,res)=>{const p=findPhoto(req.params.id);if(!p)return res.sendStatus(404);const filename=`${safeName(path.parse(p.name).name)}-external-${Date.now()}.tiff`,out=path.join(DIRS.exports,filename),ef=await writeJsonTmp(p.edits,'e'),of=await writeJsonTmp({quality:100,includeMetadata:true},'o');try{await engine(['render','--input',path.join(DIRS.originals,p.originalPath),'--output',out,'--edits',ef,'--options',of],{timeout:600000});res.json({filename,url:`/media/export/${encodeURIComponent(filename)}`})}finally{fsp.rm(ef,{force:true});fsp.rm(of,{force:true})}});

// Simple plug-in system. Drop a manifest.json plus executable/script under /var/data/plugins/<name>/.
const PLUGIN_DIR=path.join(ROOT,'plugins');fs.mkdirSync(PLUGIN_DIR,{recursive:true});
app.get('/api/plugins',async(_req,res)=>{const dirs=await fsp.readdir(PLUGIN_DIR,{withFileTypes:true}).catch(()=>[]),items=[];for(const d of dirs.filter(x=>x.isDirectory())){try{const m=JSON.parse(await fsp.readFile(path.join(PLUGIN_DIR,d.name,'manifest.json'),'utf8'));items.push({...m,folder:d.name})}catch{}}res.json(items)});
app.post('/api/plugins/:folder/run',async(req,res)=>{try{const folder=path.basename(req.params.folder),base=path.join(PLUGIN_DIR,folder),m=JSON.parse(await fsp.readFile(path.join(base,'manifest.json'),'utf8')),p=findPhoto(req.body.photoId);if(!p)return res.status(404).json({error:'Photo not found'});const executable=path.resolve(base,m.executable||'plugin.py');if(!executable.startsWith(base))return res.status(400).json({error:'Invalid plugin executable'});const out=path.join(DIRS.tmp,`${uid('plugin')}.jpg`);const cmd=m.runtime==='python'?PY:executable,args=m.runtime==='python'?[executable,path.join(DIRS.originals,p.originalPath),out,JSON.stringify(req.body.options||{})]:[path.join(DIRS.originals,p.originalPath),out,JSON.stringify(req.body.options||{})];await run(cmd,args,{timeout:600000});if(!fs.existsSync(out))return res.json({ok:true});const generated=await importGenerated(out,`${path.parse(p.name).name}-${m.name||folder}.jpg`);await fsp.rm(out,{force:true});res.json({ok:true,generatedPhoto:generated})}catch(e){res.status(500).json({error:e.message})}});

app.patch('/api/settings',async(req,res)=>{db.settings={...db.settings,...req.body};await saveDB();res.json(db.settings)});

app.use((err,req,res,next)=>{console.error(err);if(res.headersSent)return next(err);res.status(500).json({error:err.message||'Server error'})});
app.use((_req,res)=>res.sendFile(path.resolve('public/index.html')));
app.listen(PORT,()=>console.log(`Lumina listening on ${PORT}; data: ${ROOT}`));
